<a href="https://colab.research.google.com/github/Darkunquie/FMML_PROJECT_2024/blob/main/colab_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a = [[11,22,44,55],[2,3,4,5]]
b = np.transpose(a)
print('a\n',a)
print('b\n',b)

a
 [[11, 22, 44, 55], [2, 3, 4, 5]]
b
 [[11  2]
 [22  3]
 [44  4]
 [55  5]]


In [5]:
print ("Matrix and its Transpose")
a = np.array([[1,2,3,4],[2,3,4,5]])
b = a.T
print('a\n',a)
print('b\n',b)

Matrix and its Transpose
a
 [[1 2 3 4]
 [2 3 4 5]]
b
 [[1 2]
 [2 3]
 [3 4]
 [4 5]]
